# Generated by Django 2.0 on 2019-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_auto_20190109_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Pacientes', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
