# Generated by Django 2.0 on 2019-01-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20190109_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name_plural': 'Turnos'},
        ),
    ]
