# Generated by Django 2.0 on 2019-01-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20190109_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(verbose_name=['%Y-%m-%d']),
        ),
    ]
