# Generated by Django 2.0 on 2019-01-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_auto_20190113_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(verbose_name='%a %b %d %H:%M:%S %Y'),
        ),
    ]
