# Generated by Django 2.0 on 2019-01-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_auto_20190113_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
    ]
