# Generated by Django 2.0.2 on 2019-01-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_auto_20190118_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='turno',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
