# Generated by Django 2.0.2 on 2019-01-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_auto_20190118_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('obra_social', models.CharField(max_length=50)),
            ],
        ),
    ]
