# Generated by Django 2.0.2 on 2019-01-22 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0017_auto_20190122_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
