# Generated by Django 2.0 on 2018-12-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20181227_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
